
// 封装函数

// 自调用匿名函数
(function(){
    var kids ='';

})()

// 函数表达式
var kids= function(){
    var a='';

    return   ;
}

// 函数
function kids(){
     var a ='';


     return   ;
}
console.log( kids());



// 创建数组
var arr =[];
arr[i]='';
arr.forEach(function(){


});

// 用函数构建数组
var arr4= new Array('','','','','','','');


// 从数组的末尾插入一个或者多个元素
var arr1 =[];
arr1.push('','','','','','');

// 删除数组最后一个元素
var arr2 =[];
var last=arr2.pop();
console.log(last);

// 按照顺序排列数组
var arr3=[];
var pai = arr3.sort(function(a,b){
return a-b;
});


// while循环
while(true){




};

// do-while循环(先执行一次再循环)
do{




}while(true){



};

// if-else条件
if(){


}else{

};

// if-else-if 条件
if(){

}else if(){

}else if(){

}else if(){

}else if(){

}else if(){

}else{

};

// switch-case  固定假设
switch(){
   case'':

   break;
   case'':

   break;
   case'':

   break;
   case'':

   break;
   case'':

   break;

   default:
       break;
}


// 构造函数
function Kids(){
    this.   ='';
    this.   ='';
    this.   ='';
    this.   ='';
    this.  =function(){


        return;
    }
    this.  =function(){


        return;
    }
    this.  =function(){


        return;
    }
    this.  =function(){


        return;
    }
    this.  =function(){


        return;
    }
};
var pp= new Kids();

// 获取当前时间
var date= new Date();




